#!/usr/bin/env python

import sys
import commands
from pytoggl import PyToggl

token = ""
entryName = "Entry created on git-hook"

def main():
    branchname = commands.getoutput("git branch | grep '*' | sed 's/* //'")
    pt = PyToggl(token)
    pt.setVerbose(True)

    current = pt.getCurrent()
    if current is False:
        print 'Entry-retrieval went wrong. Exit!'
        return 1

    if current is None:
	    workspace = pt.getWorkspace()
	    if not workspace:
	        print 'Cannot find a workspace to create entry in. Exit!'
	        return 1

	    #create entry
	    current = pt.createEntry(workspace['id'], entryName )
	    if not current:
	        print 'Failed creating a workspace. Exit!'
	        return 1

    # Entry is running
    tag = pt.createTag(current['wid'], branchname)
    if not tag:
        print 'Failed finding or creating the tag. Exit!'
        return 1

    return pt.addTagToEntry(current, tag['name'])

if __name__ == "__main__":
    exit(main())
